import FMHost, {Container, LayoutInterface} from "@jd-data-limited/easy-fm";
// 2 layouts found

const HOST = new FMHost("https://carlson45-d.jd-data.com", "780", "true");
HOST.database<{
    layouts: { "Web_API_Dexie_Changes": Web_API_Dexie_ChangesLayoutInterface, "API_Assets": API_AssetsLayoutInterface }
}>();

const LAYOUTS = {
    WEB_API_DEXIE_CHANGES: HOST.getLayout<Web_API_Dexie_ChangesLayoutInterface>("Web_API_Dexie_Changes"),
    API_ASSETS: HOST.getLayout<API_AssetsLayoutInterface>("API_Assets")
};

export interface Web_API_Dexie_ChangesLayoutInterface extends LayoutInterface {
    fields: {
        "Data": Field<string>,
        "Table": Field<string>,
        "PrimaryKey": Field<string>,
        "ModificationTimestamp": Field<Date>,
        "CreationTimestamp": Field<Date>
    },
    portals: {}
}

export interface API_AssetsLayoutInterface extends LayoutInterface {
    fields: {
        "Age": Field<string>,
        "Artwork": Field<string>,
        "Asset Type": Field<string>,
        "asset_id_geo": Field<string>,
        "asset_id_neighbourhood": Field<string>,
        "asset_id_spider": Field<string>,
        "asset_id_station": Field<string>,
        "bus_audit_complete_user": Field<string>,
        "bus_object_id": Field<string>,
        "bus_pid_attachments": Field<string>,
        "bus_pid_id": Field<string>,
        "bus_pid_notes": Field<string>,
        "bus_pid_type": Field<string>,
        "bus_pid_working": Field<string>,
        "bus_route_list": Field<string>,
        "bus_shelter": Field<string>,
        "bus_stop_address": Field<string>,
        "bus_stop_category": Field<string>,
        "bus_stop_id": Field<string>,
        "bus_stop_name": Field<string>,
        "bus_stop_parentStation_id": Field<string>,
        "Condition": Field<string>,
        "Created By": Field<string>,
        "damages_list": Field<string>,
        "dropbox_api_post_main": Field<string>,
        "dropbox_api_post_photo_1": Field<string>,
        "dropbox_api_post_photo_2": Field<string>,
        "id_station": Field<string>,
        "illuminated_list": Field<string>,
        "IMPORT_Latitude": Field<string>,
        "IMPORT_Longitude": Field<string>,
        "IMPORT_StopName": Field<string>,
        "IMPORT_StopType": Field<string>,
        "IMPORT_TrainStation": Field<string>,
        "is_rnr": Field<string>,
        "latitude": Field<string>,
        "line_type": Field<string>,
        "location_values": Field<string>,
        "longitude": Field<string>,
        "notes": Field<string>,
        "photo_1_dropbox_api_return": Field<string>,
        "photo_2_dropbox_api_return": Field<string>,
        "photo_main_dropbox_api_return": Field<string>,
        "photo_temp_number": Field<string>,
        "substrate": Field<string>,
        "Train Line": Field<string>,
        "Train Station": Field<string>,
        "zflag_bus_audit_complete": Field<string>,
        "zflag_flag": Field<string>,
        "zflag_geoMap": Field<string>,
        "zflag_neighMap": Field<string>,
        "zflag_optimised": Field<string>,
        "zflag_pid": Field<string>,
        "zflag_poleMapTT": Field<string>,
        "zflag_rp5": Field<string>,
        "zflag_shelter": Field<string>,
        "zflag_spiderMap": Field<string>,
        "zflag_stationMap": Field<string>,
        "zrec_modified_by": Field<string>,
        "zrec_status": Field<string>,
        "zzrec_id": Field<string>,
        "dimension_height": Field<number>,
        "dimension_thickness": Field<number>,
        "dimension_width": Field<number>,
        "fileSize_processedFlag": Field<number>,
        "flag": Field<number>,
        "lock": Field<number>,
        "serial": Field<number>,
        "zflag_bilingual": Field<number>,
        "bus_audit_complete_timestamp": Field<Date>,
        "Date Time Created": Field<Date>,
        "fileSize_processedTimestamp": Field<Date>,
        "zrec_modification_timestamp": Field<Date>,
        "photo_1": Field<Container>,
        "photo_2": Field<Container>,
        "photo_3": Field<Container>,
        "photo_4": Field<Container>,
        "photo_bus_audit_flag_back": Field<Container>,
        "photo_bus_audit_flag_front": Field<Container>,
        "photo_cluster_back": Field<Container>,
        "photo_cluster_front": Field<Container>,
        "photo_geo_route_map": Field<Container>,
        "photo_live_text": Field<Container>,
        "photo_main": Field<Container>,
        "photo_neighbourhood_interchange_plan": Field<Container>,
        "photo_pid_back": Field<Container>,
        "photo_pid_front": Field<Container>,
        "photo_rp5_back": Field<Container>,
        "photo_rp5_front": Field<Container>,
        "photo_spider_map": Field<Container>,
        "photo_station_map": Field<Container>,
        "photo_temp": Field<Container>,
        "photo_zoom": Field<Container>,
        "sketch": Field<Container>,
        "container_attribute": Field<string>,
        "Damages": Field<string>,
        "IMPORT_TrainStation_Calc": Field<string>,
        "photo_1_dropbox_url": Field<string>,
        "photo_1_path": Field<string>,
        "photo_2_dropbox_url": Field<string>,
        "photo_2_path": Field<string>,
        "photo_main_dropbox_url": Field<string>,
        "photo_main_path": Field<string>,
        "zAssetJSON": Field<string>,
        "zkey_age": Field<string>,
        "zkey_bilingual": Field<string>,
        "zkey_bus_id": Field<string>,
        "zkey_bus_route": Field<string>,
        "zkey_complete": Field<string>,
        "zkey_condition": Field<string>,
        "zkey_flag": Field<string>,
        "zkey_geoMap": Field<string>,
        "zkey_lines": Field<string>,
        "zkey_neighMap": Field<string>,
        "zkey_pid": Field<string>,
        "zkey_pole": Field<string>,
        "zkey_poleMapTT": Field<string>,
        "zkey_rp5": Field<string>,
        "zkey_shelter": Field<string>,
        "zkey_spiderMap": Field<string>,
        "zkey_station": Field<string>,
        "zkey_stationMap": Field<string>,
        "zkey_type": Field<string>,
        "zkey_user": Field<string>,
        "zkey_year": Field<string>,
        "photo_1_over2mb": Field<number>,
        "photo_2_over2mb": Field<number>,
        "photo_3_over2mb": Field<number>,
        "photo_main_over2mb": Field<number>,
        "Year Audited": Field<number>,
        "zconst_active": Field<number>,
        "zconst_one": Field<number>,
        "zrec_count": Field<number>,
        "zkey_complete_timstamp": Field<Date>
    },
    portals: {}
}
