import {mkdir, rename, rm, writeFile} from 'node:fs/promises'
import {dirname, resolve} from 'node:path'
import type {
    TypegenConfig,
    TypegenDatabaseConfig,
    TypegenField,
    TypegenLayout,
    TypegenSchema,
    TypegenValidator
} from './types.js'
import {zodTypegenValidator} from './zod.js'

interface GeneratedDatabase {key: string, config: TypegenDatabaseConfig, schema: TypegenSchema, validator: TypegenValidator}

export async function generate (config: TypegenConfig): Promise<{output: string, layouts: number, databases: number}> {
    const databases = await Promise.all(databaseEntries(config).map(async ([key, databaseConfig]) => {
        const discovered = await databaseConfig.source.introspect()
        const selected = databaseConfig.layouts ? discovered.layouts.filter(layout => databaseConfig.layouts!.includes(layout.name)) : discovered.layouts
        const missing = databaseConfig.layouts?.filter(name => !selected.some(layout => layout.name === name)) ?? []
        if (missing.length) throw new Error(`Layouts not found in database ${key}: ${missing.join(', ')}`)
        return {key, config: databaseConfig, schema: {version: 1, layouts: [...selected].sort((a, b) => a.name.localeCompare(b.name))} as TypegenSchema, validator: databaseConfig.validator ?? config.validator ?? zodTypegenValidator()}
    }))
    const output = resolve(config.output); const temporary = `${output}.tmp-${process.pid}`
    await rm(temporary, {recursive: true, force: true}); await mkdir(temporary, {recursive: true})
    await writeFile(resolve(temporary, 'client.ts'), renderClient(databases), 'utf8')
    const manifest = {version: 1, databases: Object.fromEntries(databases.map(db => [db.key, {...db.schema, provider: db.config.provider, transports: db.config.transports ?? ['data-api', 'odata']}]))}
    await writeFile(resolve(temporary, 'schema.json'), `${JSON.stringify(manifest, null, 2)}\n`, 'utf8')
    await mkdir(dirname(output), {recursive: true}); await rm(output, {recursive: true, force: true}); await rename(temporary, output)
    return {output, databases: databases.length, layouts: databases.reduce((sum, db) => sum + db.schema.layouts.length, 0)}
}

function databaseEntries (config: TypegenConfig): Array<[string, TypegenDatabaseConfig]> {
    if (config.databases && Object.keys(config.databases).length) return Object.entries(config.databases)
    if (!config.source) throw new Error('Typegen config requires source or databases')
    return [['database', {source: config.source, transports: config.transports, layouts: config.layouts, validator: config.validator}]]
}

function renderClient (databases: GeneratedDatabase[]) {
    const imports = [...new Set(databases.flatMap(db => db.validator.imports))].join('\n')
    const interfaces = databases.flatMap(db => db.schema.layouts.map(layout => renderLayout(db.key, layout))).join('\n\n')
    const structures = databases.map(db => `export interface ${databaseType(db.key)} extends DatabaseStructure {\n    layouts: {${db.schema.layouts.map(layout => `${quote(layout.name)}: ${layoutTypeName(db.key, layout)}`).join(',')}}\n}`).join('\n\n')
    const schemas = databases.map(db => `${prop(db.key)}: {validator: ${db.validator.runtimeValidator}, layouts: {${db.schema.layouts.map(layout => `${quote(layout.name)}: {record: ${db.validator.renderRecord(layout)}, metadata: ${renderMetadata(layout)}}`).join(',')}}}`).join(',')
    const factories = databases.map(db => `function create${typeId(db.key, 'Database')}Client (provider: DatabaseProvider) {\n    const database = Database.create<${databaseType(db.key)}>({provider: withSchemaValidation(provider, easyFMSchemas.${prop(db.key)})})\n    return {database, ${db.schema.layouts.map(layout => `${prop(layout.clientName ?? layout.name)}: database.layout<${layoutTypeName(db.key, layout)}>(${quote(layout.name)})`).join(',')}}\n}`).join('\n\n')
    return `/* Generated by easyfm typegen. Do not edit. */
import {Database, withSchemaValidation, zodValidator, type DatabaseProvider, type DatabaseStructure, type LayoutInterface, type Portal, type ReadonlyField, type TextField, type NumberField, type DateField, type TimeField, type TimeStampField, type ContainerField} from '@jd-data-limited/easy-fm'
${imports}
${interfaces}
${structures}
export const easyFMSchemas = {${schemas}}
${factories}
export function createEasyFMClient (providers: {${databases.map(db => `${prop(db.key)}: DatabaseProvider`).join(',')}}) { return {${databases.map(db => `${prop(db.key)}: create${typeId(db.key, 'Database')}Client(providers.${prop(db.key)})`).join(',')}} }
`
}

function renderLayout (db: string, layout: TypegenLayout) { return `export interface ${layoutTypeName(db, layout)} extends LayoutInterface { fields: {${layout.fields.map(f => `${quote(f.name)}: ${fieldType(f)}`).join(',')}}; portals: {${Object.entries(layout.portals).map(([name, fields]) => `${quote(name)}: Portal<{${fields.map(f => `${quote(f.name)}: ${fieldType(f)}`).join(',')}}>`).join(',')}} }` }
function fieldType (f: TypegenField) { const t = ({text: 'TextField', number: 'NumberField', date: 'DateField', time: 'TimeField', timeStamp: 'TimeStampField', container: 'ContainerField'} as const)[f.result]; return f.writable ? t : `ReadonlyField<${t}>` }
function renderMetadata (layout: TypegenLayout) { return `{fields: ${metadataFields(layout.fields)}, portals: {${Object.entries(layout.portals).map(([name, fields]) => `${quote(name)}: ${metadataFields(fields)}`).join(',')}}}` }
function metadataFields (fields: readonly TypegenField[]) { return `{${fields.map(f => `${quote(f.name)}: {result: ${quote(f.result)}, type: ${quote(f.type)}}`).join(',')}}` }
function databaseType (db: string) { return `${typeId(db, 'Database')}Database` }
function layoutTypeName (db: string, layout: TypegenLayout) { return `${typeId(db, 'Database')}${typeId(layout.clientName ?? layout.name, 'Layout')}Layout` }
function prop (value: string) { return id(value, 'item') }
function typeId (value: string, fallback: string) { const valueId = id(value, fallback); return valueId[0].toUpperCase() + valueId.slice(1) }
function id (value: string, fallback: string) { const clean = value.replace(/[^a-zA-Z0-9_$]/g, '_').replace(/^[^a-zA-Z_$]+/, ''); return clean || fallback }
function quote (value: string) { return JSON.stringify(value) }
