import {mkdir, rename, rm, writeFile} from 'node:fs/promises'
import {dirname, resolve} from 'node:path'
import type {TypegenConfig, TypegenField, TypegenLayout, TypegenSchema, TypegenValidator} from './types.js'
import {zodTypegenValidator} from './zod.js'

export async function generate (config: TypegenConfig): Promise<{output: string, layouts: number}> {
    const discovered = await config.source.introspect()
    const selected = config.layouts ? discovered.layouts.filter(layout => config.layouts!.includes(layout.name)) : discovered.layouts
    const missing = config.layouts?.filter(name => !selected.some(layout => layout.name === name)) ?? []
    if (missing.length) throw new Error(`Layouts not found: ${missing.join(', ')}`)
    const schema: TypegenSchema = {version: 1, layouts: [...selected].sort((a, b) => a.name.localeCompare(b.name))}
    const output = resolve(config.output)
    const temporary = `${output}.tmp-${process.pid}`
    await rm(temporary, {recursive: true, force: true})
    await mkdir(temporary, {recursive: true})
    await writeFile(resolve(temporary, 'client.ts'), renderClient(schema, config.validator ?? zodTypegenValidator()), 'utf8')
    await writeFile(resolve(temporary, 'schema.json'), `${JSON.stringify({...schema, transports: config.transports ?? ['data-api', 'odata']}, null, 2)}\n`, 'utf8')
    await mkdir(dirname(output), {recursive: true})
    await rm(output, {recursive: true, force: true})
    await rename(temporary, output)
    return {output, layouts: schema.layouts.length}
}

function renderClient (schema: TypegenSchema, validator: TypegenValidator) {
    const interfaces = schema.layouts.map(renderLayout).join('\n\n')
    const structure = schema.layouts.map(layout => `${quote(layout.name)}: ${layoutTypeName(layout)}`).join(',\n        ')
    const validators = schema.layouts.map(layout => `${quote(layout.name)}: {\n        record: ${validator.renderRecord(layout)},\n        metadata: ${renderMetadata(layout)}\n    }`).join(',\n    ')
    const properties = schema.layouts.map(layout => `${safeProperty(layout.clientName ?? layout.name)}: database.layout<${layoutTypeName(layout)}>(${quote(layout.name)})`).join(',\n        ')
    return `/* Generated by easyfm typegen. Do not edit. */
import {Database, withSchemaValidation, ${validator.runtimeValidator}, type DatabaseProvider, type DatabaseStructure, type LayoutInterface, type Portal, type ReadonlyField, type TextField, type NumberField, type DateField, type TimeField, type TimeStampField, type ContainerField} from '@jd-data-limited/easy-fm'
${validator.imports.join('\n')}

${interfaces}

export interface GeneratedDatabase extends DatabaseStructure {
    layouts: {
        ${structure}
    }
}

export const easyFMSchema = {
    validator: ${validator.runtimeValidator},
    layouts: {
        ${validators}
    }
} satisfies Parameters<typeof withSchemaValidation>[1]

export function createEasyFMClient (provider: DatabaseProvider) {
    const database = Database.create<GeneratedDatabase>({provider: withSchemaValidation(provider, easyFMSchema)})
    return {
        database,
        ${properties}
    }
}
`
}

function renderLayout (layout: TypegenLayout) {
    const fields = layout.fields.map(field => `${quote(field.name)}: ${fieldType(field)}`).join('\n        ')
    const portals = Object.entries(layout.portals).map(([name, portalFields]) => `${quote(name)}: Portal<{\n            ${portalFields.map(field => `${quote(field.name)}: ${fieldType(field)}`).join('\n            ')}\n        }>`).join('\n        ')
    return `export interface ${layoutTypeName(layout)} extends LayoutInterface {
    fields: {
        ${fields}
    }
    portals: {
        ${portals}
    }
}`
}

function fieldType (field: TypegenField) {
    const type = ({text: 'TextField', number: 'NumberField', date: 'DateField', time: 'TimeField', timeStamp: 'TimeStampField', container: 'ContainerField'} as const)[field.result]
    return field.writable ? type : `ReadonlyField<${type}>`
}

function renderMetadata (layout: TypegenLayout) {
    const fields = renderMetadataFields(layout.fields)
    const portals = Object.entries(layout.portals).map(([name, portalFields]) => `${quote(name)}: ${renderMetadataFields(portalFields)}`).join(', ')
    return `{fields: ${fields}, portals: {${portals}}}`
}

function renderMetadataFields (fields: readonly TypegenField[]) {
    return `{${fields.map(field => `${quote(field.name)}: {result: ${quote(field.result)}, type: ${quote(field.type)}}`).join(', ')}}`
}

function layoutTypeName (layout: TypegenLayout) { return `${identifier(layout.clientName ?? layout.name, 'Layout')}Layout` }
function safeProperty (value: string) { return identifier(value, 'layout') }
function identifier (value: string, fallback: string) {
    const cleaned = value.replace(/[^a-zA-Z0-9_$]/g, '_').replace(/^[^a-zA-Z_$]+/, '')
    return cleaned || fallback
}
function quote (value: string) { return JSON.stringify(value) }
