/* Generated by easyfm typegen. Do not edit. */
import {
    type ContainerField,
    Database,
    type DatabaseProvider,
    type DatabaseStructure,
    type DateField,
    type LayoutInterface,
    type Portal,
    type TextField,
    type TimeField,
    type TimeStampField,
    withSchemaValidation,
    zodValidator
} from '@jd-data-limited/easy-fm'
import {z} from 'zod'

export interface EasyFMBenchmarkLayout extends LayoutInterface {
    fields: {
        "OneVeryLongField": TextField
        "PrimaryKey": TextField
        "CreationTimestamp": TimeStampField
        "Date": DateField
        "Time": TimeField
        "Timestamp": TimeStampField
        "Container": ContainerField
        "AVeryStrictField": TextField
    }
    portals: {
        "test": Portal<{
            "test::PrimaryKey": TextField
            "test::CreationTimestamp": TimeStampField
            "test::CreatedBy": TextField
            "test::ModificationTimestamp": TimeStampField
            "test::ModifiedBy": TextField
            "test::OneVeryLongField": TextField
        }>
    }
}

export interface OriginLayout extends LayoutInterface {
    fields: {
        "Country": TextField
        "PrimaryKey": TextField
    }
    portals: {
        
    }
}

export interface SpecimenLayout extends LayoutInterface {
    fields: {
        "TaxonomyID": TextField
        "OriginID": TextField
    }
    portals: {
        
    }
}

export interface TaxonomyLayout extends LayoutInterface {
    fields: {
        "Name": TextField
        "PrimaryKey": TextField
    }
    portals: {
        
    }
}

export interface GeneratedDatabase extends DatabaseStructure {
    layouts: {
        "EasyFMBenchmark": EasyFMBenchmarkLayout,
        "Origin": OriginLayout,
        "Specimen": SpecimenLayout,
        "Taxonomy": TaxonomyLayout
    }
}

export const easyFMSchema = {
    validator: zodValidator,
    layouts: {
        "EasyFMBenchmark": {
        record: z.object({recordId: z.string(), modId: z.string(), fieldData: z.object({"OneVeryLongField": z.string(), "PrimaryKey": z.string(), "CreationTimestamp": z.string().nullable(), "Date": z.string().nullable(), "Time": z.string().nullable(), "Timestamp": z.string().nullable(), "Container": z.string().nullable(), "AVeryStrictField": z.string()}).strict(), portalData: z.object({"test": z.array(z.object({"test::PrimaryKey": z.string(), "test::CreationTimestamp": z.string().nullable(), "test::CreatedBy": z.string(), "test::ModificationTimestamp": z.string().nullable(), "test::ModifiedBy": z.string(), "test::OneVeryLongField": z.string(), recordId: z.union([z.string(), z.number()]), modId: z.union([z.string(), z.number()])}).strict())}).partial().strict().optional()}).strict(),
        metadata: {fields: {"OneVeryLongField": {result: "text", type: "normal"}, "PrimaryKey": {result: "text", type: "normal"}, "CreationTimestamp": {result: "timeStamp", type: "normal"}, "Date": {result: "date", type: "normal"}, "Time": {result: "time", type: "normal"}, "Timestamp": {result: "timeStamp", type: "normal"}, "Container": {result: "container", type: "normal"}, "AVeryStrictField": {result: "text", type: "normal"}}, portals: {"test": {"test::PrimaryKey": {result: "text", type: "normal"}, "test::CreationTimestamp": {result: "timeStamp", type: "normal"}, "test::CreatedBy": {result: "text", type: "normal"}, "test::ModificationTimestamp": {result: "timeStamp", type: "normal"}, "test::ModifiedBy": {result: "text", type: "normal"}, "test::OneVeryLongField": {result: "text", type: "normal"}}}}
    },
    "Origin": {
        record: z.object({recordId: z.string(), modId: z.string(), fieldData: z.object({"Country": z.string(), "PrimaryKey": z.string()}).strict(), portalData: z.object({}).partial().strict().optional()}).strict(),
        metadata: {fields: {"Country": {result: "text", type: "normal"}, "PrimaryKey": {result: "text", type: "normal"}}, portals: {}}
    },
    "Specimen": {
        record: z.object({recordId: z.string(), modId: z.string(), fieldData: z.object({"TaxonomyID": z.string(), "OriginID": z.string()}).strict(), portalData: z.object({}).partial().strict().optional()}).strict(),
        metadata: {fields: {"TaxonomyID": {result: "text", type: "normal"}, "OriginID": {result: "text", type: "normal"}}, portals: {}}
    },
    "Taxonomy": {
        record: z.object({recordId: z.string(), modId: z.string(), fieldData: z.object({"Name": z.string(), "PrimaryKey": z.string()}).strict(), portalData: z.object({}).partial().strict().optional()}).strict(),
        metadata: {fields: {"Name": {result: "text", type: "normal"}, "PrimaryKey": {result: "text", type: "normal"}}, portals: {}}
    }
    }
} satisfies Parameters<typeof withSchemaValidation>[1]

export function createEasyFMClient (provider: DatabaseProvider) {
    const database = Database.create<GeneratedDatabase>({provider: withSchemaValidation(provider, easyFMSchema)})
    return {
        database,
        EasyFMBenchmark: database.layout<EasyFMBenchmarkLayout>("EasyFMBenchmark"),
        Origin: database.layout<OriginLayout>("Origin"),
        Specimen: database.layout<SpecimenLayout>("Specimen"),
        Taxonomy: database.layout<TaxonomyLayout>("Taxonomy")
    }
}
